//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WytSky.Mobile.Maui.Hadrein.AppResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WytSky.Mobile.Maui.Hadrein.AppResources.SharedResources", typeof(SharedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kuwait - Salmiya - St. Salem Al Mubarak - Ganja Pulse.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back_01_EN.png.
        /// </summary>
        public static string Image_Back_01 {
            get {
                return ResourceManager.GetString("Image_Back_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BackW_01_EN.png.
        /// </summary>
        public static string Image_BackW_01 {
            get {
                return ResourceManager.GetString("Image_BackW_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an acoount ?.
        /// </summary>
        public static string Msg_AlreadyHaveAcoount {
            get {
                return ResourceManager.GetString("Msg_AlreadyHaveAcoount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to close the application?.
        /// </summary>
        public static string Msg_CloseApp {
            get {
                return ResourceManager.GetString("Msg_CloseApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Internet Connection , Make sure that Wi-Fi or mobile data is turned on , then try again.
        /// </summary>
        public static string Msg_ConnectionError {
            get {
                return ResourceManager.GetString("Msg_ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don’t have an acoount ?.
        /// </summary>
        public static string Msg_DontHaveAcoount {
            get {
                return ResourceManager.GetString("Msg_DontHaveAcoount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you have already entered an email already in use.
        /// </summary>
        public static string Msg_EmailAlreadyUse {
            get {
                return ResourceManager.GetString("Msg_EmailAlreadyUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry : you have entered an e-mail address that does not exist. Please make sure that you are using the data of an account already registered
        ///If you do not have an account, you can register now.
        /// </summary>
        public static string Msg_EmailNotValid {
            get {
                return ResourceManager.GetString("Msg_EmailNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry: An error has occurred, try again.
        /// </summary>
        public static string Msg_Error {
            get {
                return ResourceManager.GetString("Msg_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry : no data is available for viewing at this time.
        /// </summary>
        public static string Msg_NoData {
            get {
                return ResourceManager.GetString("Msg_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data Found.
        /// </summary>
        public static string Msg_NoDataFound {
            get {
                return ResourceManager.GetString("Msg_NoDataFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Internet Connection , Make sure that Wi-Fi or mobile data is turned on , then try again.
        /// </summary>
        public static string Msg_NoInternetConnection {
            get {
                return ResourceManager.GetString("Msg_NoInternetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry: .... Service is not available at the time of the area you have chosen.
        ///Do you want us to notify you when the service is available?.
        /// </summary>
        public static string Msg_NotAvailabelService {
            get {
                return ResourceManager.GetString("Msg_NotAvailabelService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry: you entered an incorrect email.
        /// </summary>
        public static string Msg_NotValidEmail {
            get {
                return ResourceManager.GetString("Msg_NotValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry : you entered an incorrect Message.
        /// </summary>
        public static string Msg_NotValidMessage {
            get {
                return ResourceManager.GetString("Msg_NotValidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry: you entered an incorrect name.
        /// </summary>
        public static string Msg_NotValidName {
            get {
                return ResourceManager.GetString("Msg_NotValidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry : you entered an incorrect New Password.
        /// </summary>
        public static string Msg_NotValidNewPassword {
            get {
                return ResourceManager.GetString("Msg_NotValidNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry : you entered an incorrect Code.
        /// </summary>
        public static string Msg_NotValidOrgCode {
            get {
                return ResourceManager.GetString("Msg_NotValidOrgCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry : you entered an incorrect Password.
        /// </summary>
        public static string Msg_NotValidPassword {
            get {
                return ResourceManager.GetString("Msg_NotValidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry: you have entered an incorrect phone number.
        /// </summary>
        public static string Msg_NotValidPhone {
            get {
                return ResourceManager.GetString("Msg_NotValidPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry : you entered an incorrect UserName.
        /// </summary>
        public static string Msg_NotValidUserName {
            get {
                return ResourceManager.GetString("Msg_NotValidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry : you entered an incorrect Description.
        /// </summary>
        public static string Msg_NoValidDescription {
            get {
                return ResourceManager.GetString("Msg_NoValidDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry : you entered an incorrect Name.
        /// </summary>
        public static string Msg_NoValidName {
            get {
                return ResourceManager.GetString("Msg_NoValidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry: the password and confirm the password mismatch.
        /// </summary>
        public static string Msg_PasswordNotMatch {
            get {
                return ResourceManager.GetString("Msg_PasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 8 characters long and contain numbers, letters and @.
        /// </summary>
        public static string Msg_PasswordValdation {
            get {
                return ResourceManager.GetString("Msg_PasswordValdation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are messages that have not been sent, they will be sent automatically as soon as an internet connection is available.
        /// </summary>
        public static string Msg_SendNewMessage {
            get {
                return ResourceManager.GetString("Msg_SendNewMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Expired, Please Login Again.
        /// </summary>
        public static string Msg_SessionExpired {
            get {
                return ResourceManager.GetString("Msg_SessionExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry : this account cannot be reset because it does not contain a password. You have logged in through a social media site. You can log in the same way now..
        /// </summary>
        public static string Msg_SocialEmail {
            get {
                return ResourceManager.GetString("Msg_SocialEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation accomplished successfully.
        /// </summary>
        public static string Msg_Success {
            get {
                return ResourceManager.GetString("Msg_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry: the time limit has expired. Please log in again.
        /// </summary>
        public static string Msg_TimeExpired {
            get {
                return ResourceManager.GetString("Msg_TimeExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry: we were not able to locate your current location. This may be due to the lack of permission for the application to determine the location or because the GPS feature has not been activated on your device
        ///You can activate the location feature or manually locate your site in order to benefit from our services.
        /// </summary>
        public static string Msg_UnableGetLocation {
            get {
                return ResourceManager.GetString("Msg_UnableGetLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry: this user is not authorized to use the application at this time, you must contact the administration to find out the reason.
        /// </summary>
        public static string Msg_UserNoValid {
            get {
                return ResourceManager.GetString("Msg_UserNoValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the code that you received on the e-mail.
        /// </summary>
        public static string Msg_VerficationCode {
            get {
                return ResourceManager.GetString("Msg_VerficationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organiztion Code.
        /// </summary>
        public static string Test_OrganiztionCode {
            get {
                return ResourceManager.GetString("Test_OrganiztionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AboutUs.
        /// </summary>
        public static string Text_AboutUs {
            get {
                return ResourceManager.GetString("Text_AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Text_Add {
            get {
                return ResourceManager.GetString("Text_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Bonus to delivery.
        /// </summary>
        public static string Text_AddBonusToDelivery {
            get {
                return ResourceManager.GetString("Text_AddBonusToDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        public static string Text_AddNew {
            get {
                return ResourceManager.GetString("Text_AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Payment Method.
        /// </summary>
        public static string Text_AddPaymentMethod {
            get {
                return ResourceManager.GetString("Text_AddPaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Text_Address {
            get {
                return ResourceManager.GetString("Text_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Detail.
        /// </summary>
        public static string Text_AddressDetail {
            get {
                return ResourceManager.GetString("Text_AddressDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add To Cart.
        /// </summary>
        public static string Text_AddToCart {
            get {
                return ResourceManager.GetString("Text_AddToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        public static string Text_Alert {
            get {
                return ResourceManager.GetString("Text_Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string Text_All {
            get {
                return ResourceManager.GetString("Text_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login by using Apple.
        /// </summary>
        public static string Text_AppleLogin {
            get {
                return ResourceManager.GetString("Text_AppleLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Text_Apply {
            get {
                return ResourceManager.GetString("Text_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has been approved.
        /// </summary>
        public static string Text_Approval {
            get {
                return ResourceManager.GetString("Text_Approval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach File.
        /// </summary>
        public static string Text_AttachFile {
            get {
                return ResourceManager.GetString("Text_AttachFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach a Picture.
        /// </summary>
        public static string Text_AttachPicture {
            get {
                return ResourceManager.GetString("Text_AttachPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach a Video.
        /// </summary>
        public static string Text_AttachVideo {
            get {
                return ResourceManager.GetString("Text_AttachVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach a Voice.
        /// </summary>
        public static string Text_AttachVoice {
            get {
                return ResourceManager.GetString("Text_AttachVoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awaiting approval.
        /// </summary>
        public static string Text_AwaitingApproval {
            get {
                return ResourceManager.GetString("Text_AwaitingApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Text_Back {
            get {
                return ResourceManager.GetString("Text_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Sell.
        /// </summary>
        public static string Text_BestSell {
            get {
                return ResourceManager.GetString("Text_BestSell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bouns to delivery.
        /// </summary>
        public static string Text_BonusToDelivery {
            get {
                return ResourceManager.GetString("Text_BonusToDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse Products.
        /// </summary>
        public static string Text_BrowseProducts {
            get {
                return ResourceManager.GetString("Text_BrowseProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse Services.
        /// </summary>
        public static string Text_BrowseServices {
            get {
                return ResourceManager.GetString("Text_BrowseServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera.
        /// </summary>
        public static string Text_Camera {
            get {
                return ResourceManager.GetString("Text_Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera.
        /// </summary>
        public static string Text_CameraVideo {
            get {
                return ResourceManager.GetString("Text_CameraVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Text_Cancel {
            get {
                return ResourceManager.GetString("Text_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled.
        /// </summary>
        public static string Text_Canceled {
            get {
                return ResourceManager.GetString("Text_Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Order.
        /// </summary>
        public static string Text_CancelOrder {
            get {
                return ResourceManager.GetString("Text_CancelOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancle.
        /// </summary>
        public static string Text_Cancle {
            get {
                return ResourceManager.GetString("Text_Cancle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart.
        /// </summary>
        public static string Text_Cart {
            get {
                return ResourceManager.GetString("Text_Cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart Items Deleted.
        /// </summary>
        public static string Text_CartItemsDeleted {
            get {
                return ResourceManager.GetString("Text_CartItemsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CartI items saved locally and will be save when have active an internet connection .
        /// </summary>
        public static string Text_CartItemsSavedLocally {
            get {
                return ResourceManager.GetString("Text_CartItemsSavedLocally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash On Delivery.
        /// </summary>
        public static string Text_CashOnDelivery {
            get {
                return ResourceManager.GetString("Text_CashOnDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Text_Categories {
            get {
                return ResourceManager.GetString("Text_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string Text_Change {
            get {
                return ResourceManager.GetString("Text_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string Text_ChangePassword {
            get {
                return ResourceManager.GetString("Text_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Out.
        /// </summary>
        public static string Text_CheckOut {
            get {
                return ResourceManager.GetString("Text_CheckOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose.
        /// </summary>
        public static string Text_Choose {
            get {
                return ResourceManager.GetString("Text_Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a service.
        /// </summary>
        public static string Text_ChooseService {
            get {
                return ResourceManager.GetString("Text_ChooseService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Text_Close {
            get {
                return ResourceManager.GetString("Text_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close alurt.
        /// </summary>
        public static string Text_CloseApp {
            get {
                return ResourceManager.GetString("Text_CloseApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code sent to.
        /// </summary>
        public static string Text_CodeSentTo {
            get {
                return ResourceManager.GetString("Text_CodeSentTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to code will expire in.
        /// </summary>
        public static string Text_CodeWillExpireIn {
            get {
                return ResourceManager.GetString("Text_CodeWillExpireIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string Text_Completed {
            get {
                return ResourceManager.GetString("Text_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string Text_ConfirmPassword {
            get {
                return ResourceManager.GetString("Text_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congrats!.
        /// </summary>
        public static string Text_Congrats {
            get {
                return ResourceManager.GetString("Text_Congrats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContactUs.
        /// </summary>
        public static string Text_ContactUs {
            get {
                return ResourceManager.GetString("Text_ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Text_Continue {
            get {
                return ResourceManager.GetString("Text_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue as guest.
        /// </summary>
        public static string Text_ContinueAsGuest {
            get {
                return ResourceManager.GetString("Text_ContinueAsGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create account.
        /// </summary>
        public static string Text_CreateAccount {
            get {
                return ResourceManager.GetString("Text_CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card.
        /// </summary>
        public static string Text_CreditCard {
            get {
                return ResourceManager.GetString("Text_CreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Text_Date {
            get {
                return ResourceManager.GetString("Text_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deliver to.
        /// </summary>
        public static string Text_DeliverTo {
            get {
                return ResourceManager.GetString("Text_DeliverTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery.
        /// </summary>
        public static string Text_Delivery {
            get {
                return ResourceManager.GetString("Text_Delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Address.
        /// </summary>
        public static string Text_DeliveryAddress {
            get {
                return ResourceManager.GetString("Text_DeliveryAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery from restaurant name.
        /// </summary>
        public static string Text_DeliveryFromRestaurantName {
            get {
                return ResourceManager.GetString("Text_DeliveryFromRestaurantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Text_Description {
            get {
                return ResourceManager.GetString("Text_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More details ....
        /// </summary>
        public static string Text_Details {
            get {
                return ResourceManager.GetString("Text_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount 50%.
        /// </summary>
        public static string Text_Discount50 {
            get {
                return ResourceManager.GetString("Text_Discount50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Text_Done {
            get {
                return ResourceManager.GetString("Text_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t show again.
        /// </summary>
        public static string Text_DontShow {
            get {
                return ResourceManager.GetString("Text_DontShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Text_Edit {
            get {
                return ResourceManager.GetString("Text_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Text_Email {
            get {
                return ResourceManager.GetString("Text_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Me About Special Pricing.
        /// </summary>
        public static string Text_EmailMeAboutSpecialPricing {
            get {
                return ResourceManager.GetString("Text_EmailMeAboutSpecialPricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email / Phone.
        /// </summary>
        public static string Text_EmailOrPhone {
            get {
                return ResourceManager.GetString("Text_EmailOrPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter 4-digit
        ///Verification code.
        /// </summary>
        public static string Text_Enter4DigitVerificationCode {
            get {
                return ResourceManager.GetString("Text_Enter4DigitVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Your Email.
        /// </summary>
        public static string Text_EnterYourEmail {
            get {
                return ResourceManager.GetString("Text_EnterYourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Your Name.
        /// </summary>
        public static string Text_EnterYourName {
            get {
                return ResourceManager.GetString("Text_EnterYourName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Your Password.
        /// </summary>
        public static string Text_EnterYourPassword {
            get {
                return ResourceManager.GetString("Text_EnterYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Your Phone.
        /// </summary>
        public static string Text_EnterYourPhone {
            get {
                return ResourceManager.GetString("Text_EnterYourPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Text_Error {
            get {
                return ResourceManager.GetString("Text_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook.
        /// </summary>
        public static string Text_Facebook {
            get {
                return ResourceManager.GetString("Text_Facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login by using Facebook.
        /// </summary>
        public static string Text_FacebookLogin {
            get {
                return ResourceManager.GetString("Text_FacebookLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        public static string Text_Favorites {
            get {
                return ResourceManager.GetString("Text_Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Featured.
        /// </summary>
        public static string Text_Featured {
            get {
                return ResourceManager.GetString("Text_Featured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Featured Restaurant.
        /// </summary>
        public static string Text_FeaturedRestaurant {
            get {
                return ResourceManager.GetString("Text_FeaturedRestaurant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find for food or restaurant....
        /// </summary>
        public static string Text_FindFoodRestaurant {
            get {
                return ResourceManager.GetString("Text_FindFoodRestaurant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password ?.
        /// </summary>
        public static string Text_ForgotYourPassword {
            get {
                return ResourceManager.GetString("Text_ForgotYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your username ?.
        /// </summary>
        public static string Text_ForgotYourUsername {
            get {
                return ResourceManager.GetString("Text_ForgotYourUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Delivery.
        /// </summary>
        public static string Text_FreeDelivery {
            get {
                return ResourceManager.GetString("Text_FreeDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You’ve to order at least 10$ for using free delivery for 1 month..
        /// </summary>
        public static string Text_FreeDeliveryForOrder {
            get {
                return ResourceManager.GetString("Text_FreeDeliveryForOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Delivery for 1 Month!.
        /// </summary>
        public static string Text_FreeDeliveryOneMonth {
            get {
                return ResourceManager.GetString("Text_FreeDeliveryOneMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string Text_From {
            get {
                return ResourceManager.GetString("Text_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string Text_FullName {
            get {
                return ResourceManager.GetString("Text_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery.
        /// </summary>
        public static string Text_Gallery {
            get {
                return ResourceManager.GetString("Text_Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Location.
        /// </summary>
        public static string Text_GetLocation {
            get {
                return ResourceManager.GetString("Text_GetLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Url.
        /// </summary>
        public static string Text_GetUrl {
            get {
                return ResourceManager.GetString("Text_GetUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google.
        /// </summary>
        public static string Text_Google {
            get {
                return ResourceManager.GetString("Text_Google", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helps &amp; FAQs.
        /// </summary>
        public static string Text_HelpsFaqs {
            get {
                return ResourceManager.GetString("Text_HelpsFaqs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string Text_High {
            get {
                return ResourceManager.GetString("Text_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string Text_History {
            get {
                return ResourceManager.GetString("Text_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Text_Home {
            get {
                return ResourceManager.GetString("Text_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Implementation.
        /// </summary>
        public static string Text_Implementation {
            get {
                return ResourceManager.GetString("Text_Implementation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Process.
        /// </summary>
        public static string Text_InProcess {
            get {
                return ResourceManager.GetString("Text_InProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Details.
        /// </summary>
        public static string Text_ItemDetails {
            get {
                return ResourceManager.GetString("Text_ItemDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        public static string Text_Items {
            get {
                return ResourceManager.GetString("Text_Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to keep me sign in.
        /// </summary>
        public static string Text_keepMeSignIn {
            get {
                return ResourceManager.GetString("Text_keepMeSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العربية.
        /// </summary>
        public static string Text_Language {
            get {
                return ResourceManager.GetString("Text_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading ....
        /// </summary>
        public static string Text_Loading {
            get {
                return ResourceManager.GetString("Text_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Text_Location {
            get {
                return ResourceManager.GetString("Text_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Text_Login {
            get {
                return ResourceManager.GetString("Text_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login To Your Account.
        /// </summary>
        public static string Text_LoginToYourAccount {
            get {
                return ResourceManager.GetString("Text_LoginToYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        public static string Text_LogOut {
            get {
                return ResourceManager.GetString("Text_LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string Text_Low {
            get {
                return ResourceManager.GetString("Text_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string Text_Medium {
            get {
                return ResourceManager.GetString("Text_Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Text_Message {
            get {
                return ResourceManager.GetString("Text_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most Popular.
        /// </summary>
        public static string Text_MostPopular {
            get {
                return ResourceManager.GetString("Text_MostPopular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to continue with management if they do not find the right time.
        /// </summary>
        public static string Text_MsgContact {
            get {
                return ResourceManager.GetString("Text_MsgContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must login.
        /// </summary>
        public static string Text_MustLogin {
            get {
                return ResourceManager.GetString("Text_MustLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Orders.
        /// </summary>
        public static string Text_MyOrders {
            get {
                return ResourceManager.GetString("Text_MyOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        public static string Text_MyProfile {
            get {
                return ResourceManager.GetString("Text_MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Text_Name {
            get {
                return ResourceManager.GetString("Text_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nearest.
        /// </summary>
        public static string Text_Nearest {
            get {
                return ResourceManager.GetString("Text_Nearest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nearest Restaurant.
        /// </summary>
        public static string Text_NearestRestaurant {
            get {
                return ResourceManager.GetString("Text_NearestRestaurant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string Text_NewPassword {
            get {
                return ResourceManager.GetString("Text_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Text_Next {
            get {
                return ResourceManager.GetString("Text_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Text_No {
            get {
                return ResourceManager.GetString("Text_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Text_Notes {
            get {
                return ResourceManager.GetString("Text_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        public static string Text_Notification {
            get {
                return ResourceManager.GetString("Text_Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offers.
        /// </summary>
        public static string Text_Offers {
            get {
                return ResourceManager.GetString("Text_Offers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password.
        /// </summary>
        public static string Text_OldPassword {
            get {
                return ResourceManager.GetString("Text_OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or Continue With.
        /// </summary>
        public static string Text_OrContinueWith {
            get {
                return ResourceManager.GetString("Text_OrContinueWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string Text_Order {
            get {
                return ResourceManager.GetString("Text_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Again.
        /// </summary>
        public static string Text_OrderAgain {
            get {
                return ResourceManager.GetString("Text_OrderAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Details.
        /// </summary>
        public static string Text_OrderDetails {
            get {
                return ResourceManager.GetString("Text_OrderDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Now.
        /// </summary>
        public static string Text_OrderNow {
            get {
                return ResourceManager.GetString("Text_OrderNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Number.
        /// </summary>
        public static string Text_OrderNumber {
            get {
                return ResourceManager.GetString("Text_OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Text_Password {
            get {
                return ResourceManager.GetString("Text_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Reset Successfully.
        /// </summary>
        public static string Text_PasswordResetSuccessfully {
            get {
                return ResourceManager.GetString("Text_PasswordResetSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Methods.
        /// </summary>
        public static string Text_PaymentMethods {
            get {
                return ResourceManager.GetString("Text_PaymentMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal data.
        /// </summary>
        public static string Text_PersonalData {
            get {
                return ResourceManager.GetString("Text_PersonalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Text_Phone {
            get {
                return ResourceManager.GetString("Text_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place Order.
        /// </summary>
        public static string Text_PlaceOrder {
            get {
                return ResourceManager.GetString("Text_PlaceOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planing.
        /// </summary>
        public static string Text_Planing {
            get {
                return ResourceManager.GetString("Text_Planing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string Text_Play {
            get {
                return ResourceManager.GetString("Text_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string Text_Preview {
            get {
                return ResourceManager.GetString("Text_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Text_Previous {
            get {
                return ResourceManager.GetString("Text_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string Text_Priority {
            get {
                return ResourceManager.GetString("Text_Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string Text_Privacy {
            get {
                return ResourceManager.GetString("Text_Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string Text_PrivacyPolicy {
            get {
                return ResourceManager.GetString("Text_PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Text_Profile {
            get {
                return ResourceManager.GetString("Text_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Profile Is Ready To Use.
        /// </summary>
        public static string Text_ProfileReadyForUse {
            get {
                return ResourceManager.GetString("Text_ProfileReadyForUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promo code.
        /// </summary>
        public static string Text_PromoCode {
            get {
                return ResourceManager.GetString("Text_PromoCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate App.
        /// </summary>
        public static string Text_RateApp {
            get {
                return ResourceManager.GetString("Text_RateApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate Order.
        /// </summary>
        public static string Text_RateOrder {
            get {
                return ResourceManager.GetString("Text_RateOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ratings.
        /// </summary>
        public static string Text_Ratings {
            get {
                return ResourceManager.GetString("Text_Ratings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record.
        /// </summary>
        public static string Text_Record {
            get {
                return ResourceManager.GetString("Text_Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-enter Your Password.
        /// </summary>
        public static string Text_ReEnterYourPassword {
            get {
                return ResourceManager.GetString("Text_ReEnterYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Text_Register {
            get {
                return ResourceManager.GetString("Text_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re Order.
        /// </summary>
        public static string Text_ReOrder {
            get {
                return ResourceManager.GetString("Text_ReOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string Text_ResetPassword {
            get {
                return ResourceManager.GetString("Text_ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurants Offers.
        /// </summary>
        public static string Text_RestaurantsOffers {
            get {
                return ResourceManager.GetString("Text_RestaurantsOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviews.
        /// </summary>
        public static string Text_Reviews {
            get {
                return ResourceManager.GetString("Text_Reviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Text_Save {
            get {
                return ResourceManager.GetString("Text_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Text_Search {
            get {
                return ResourceManager.GetString("Text_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See all.
        /// </summary>
        public static string Text_SeeAll {
            get {
                return ResourceManager.GetString("Text_SeeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Items.
        /// </summary>
        public static string Text_SelectItems {
            get {
                return ResourceManager.GetString("Text_SelectItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Location.
        /// </summary>
        public static string Text_SelectLocation {
            get {
                return ResourceManager.GetString("Text_SelectLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Photo.
        /// </summary>
        public static string Text_SelectPhoto {
            get {
                return ResourceManager.GetString("Text_SelectPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Photo From ?.
        /// </summary>
        public static string Text_SelectPhotoFrom {
            get {
                return ResourceManager.GetString("Text_SelectPhotoFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Video.
        /// </summary>
        public static string Text_SelectVideo {
            get {
                return ResourceManager.GetString("Text_SelectVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Video From ?.
        /// </summary>
        public static string Text_SelectVideoFrom {
            get {
                return ResourceManager.GetString("Text_SelectVideoFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select which contact details should we use to reset your password.
        /// </summary>
        public static string Text_SelectWhichContact {
            get {
                return ResourceManager.GetString("Text_SelectWhichContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Ticket.
        /// </summary>
        public static string Text_SendTicket {
            get {
                return ResourceManager.GetString("Text_SendTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appropriate time to provide the service.
        /// </summary>
        public static string Text_ServicAappropriate {
            get {
                return ResourceManager.GetString("Text_ServicAappropriate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        public static string Text_Service {
            get {
                return ResourceManager.GetString("Text_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Details.
        /// </summary>
        public static string Text_ServiceDetails {
            get {
                return ResourceManager.GetString("Text_ServiceDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Request.
        /// </summary>
        public static string Text_ServiceRequest {
            get {
                return ResourceManager.GetString("Text_ServiceRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Location.
        /// </summary>
        public static string Text_SetLocation {
            get {
                return ResourceManager.GetString("Text_SetLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Text_Settings {
            get {
                return ResourceManager.GetString("Text_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share App.
        /// </summary>
        public static string Text_ShareApp {
            get {
                return ResourceManager.GetString("Text_ShareApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string Text_SignIn {
            get {
                return ResourceManager.GetString("Text_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string Text_SignUp {
            get {
                return ResourceManager.GetString("Text_SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up For Free.
        /// </summary>
        public static string Text_SignUpForFree {
            get {
                return ResourceManager.GetString("Text_SignUpForFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        public static string Text_Skip {
            get {
                return ResourceManager.GetString("Text_Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Text_Status {
            get {
                return ResourceManager.GetString("Text_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Recording.
        /// </summary>
        public static string Text_StopRecording {
            get {
                return ResourceManager.GetString("Text_StopRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Text_Subject {
            get {
                return ResourceManager.GetString("Text_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub total.
        /// </summary>
        public static string Text_Subtotal {
            get {
                return ResourceManager.GetString("Text_Subtotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Text_Success {
            get {
                return ResourceManager.GetString("Text_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical.
        /// </summary>
        public static string Text_Technical {
            get {
                return ResourceManager.GetString("Text_Technical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms and Conditions.
        /// </summary>
        public static string Text_TermsConditions {
            get {
                return ResourceManager.GetString("Text_TermsConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are items in cart must saved first.
        /// </summary>
        public static string Text_ThereAreItemsInCart {
            get {
                return ResourceManager.GetString("Text_ThereAreItemsInCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This data will be displayed in your account profile for security.
        /// </summary>
        public static string Text_ThisDataWillDisplayedInYourProfile {
            get {
                return ResourceManager.GetString("Text_ThisDataWillDisplayedInYourProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Text_Time {
            get {
                return ResourceManager.GetString("Text_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string Text_To {
            get {
                return ResourceManager.GetString("Text_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Do List.
        /// </summary>
        public static string Text_ToDoList {
            get {
                return ResourceManager.GetString("Text_ToDoList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Text_Total {
            get {
                return ResourceManager.GetString("Text_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Payment.
        /// </summary>
        public static string Text_TotalPayment {
            get {
                return ResourceManager.GetString("Text_TotalPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track Order.
        /// </summary>
        public static string Text_TrackOrder {
            get {
                return ResourceManager.GetString("Text_TrackOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trending.
        /// </summary>
        public static string Text_Trending {
            get {
                return ResourceManager.GetString("Text_Trending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try Again.
        /// </summary>
        public static string Text_TryAgain {
            get {
                return ResourceManager.GetString("Text_TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upcoming.
        /// </summary>
        public static string Text_UpComing {
            get {
                return ResourceManager.GetString("Text_UpComing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Your Photo Profile.
        /// </summary>
        public static string Text_UploadYourPhotoProfile {
            get {
                return ResourceManager.GetString("Text_UploadYourPhotoProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vat.
        /// </summary>
        public static string Text_Vat {
            get {
                return ResourceManager.GetString("Text_Vat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verfication Code.
        /// </summary>
        public static string Text_VerficationCode {
            get {
                return ResourceManager.GetString("Text_VerficationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Via Email:.
        /// </summary>
        public static string Text_ViaEmail {
            get {
                return ResourceManager.GetString("Text_ViaEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Via sms:.
        /// </summary>
        public static string Text_ViaSms {
            get {
                return ResourceManager.GetString("Text_ViaSms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View More.
        /// </summary>
        public static string Text_ViewMore {
            get {
                return ResourceManager.GetString("Text_ViewMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vodafone Cash.
        /// </summary>
        public static string Text_VodafoneCash {
            get {
                return ResourceManager.GetString("Text_VodafoneCash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher.
        /// </summary>
        public static string Text_Voucher {
            get {
                return ResourceManager.GetString("Text_Voucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Text_Warning {
            get {
                return ResourceManager.GetString("Text_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome To.
        /// </summary>
        public static string Text_WelcomeTo {
            get {
                return ResourceManager.GetString("Text_WelcomeTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Text_Yes {
            get {
                return ResourceManager.GetString("Text_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have items in your cart you need to send order ?.
        /// </summary>
        public static string Text_YouHaveCartItems {
            get {
                return ResourceManager.GetString("Text_YouHaveCartItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Location.
        /// </summary>
        public static string Text_YourLocation {
            get {
                return ResourceManager.GetString("Text_YourLocation", resourceCulture);
            }
        }
    }
}
